Repository ripe-tech/ripe-bus-api-js, pull requests merged in 2021-02, with the labels that each got.

#7 feat: consume multiple topics in one call
  js/consumer.js
  js/kafka/kafka-consumer.js
  js/kafka/kafka-retry-consumer.js
  types/consumer.d.ts
Labels: enhancement

#8 feat: add topic to callbacks
  js/kafka/kafka-consumer.js
  js/kafka/kafka-retry-consumer.js
Labels: enhancement

#9 Add metadata to the triggered bus event
  README.md
  js/base.js
  js/kafka/kafka-consumer.js
  js/kafka/kafka-producer.js
  js/kafka/kafka-retry-consumer.js
  rollup.config.js
  test/api/kafka.js
  types/base.d.ts
  types/index.d.ts
  types/kafka/index.d.ts
  types/kafka/kafka-consumer.d.ts
  types/kafka/kafka-retry-consumer.d.ts
  types/message.d.ts
  types/payload.d.ts
Labels: enhancement

#11 feat: filter multiple events
  js/kafka/kafka-consumer.js
  types/base.d.ts
  types/consumer.d.ts
  types/kafka/kafka-consumer.d.ts
  types/payload.d.ts
  types/producer.d.ts
Labels: enhancement

#13 Fix event filtering bug
  js/base.js
  js/kafka/kafka-consumer.js
Labels: bug

#15 Kafka topic name sanitizer
  js/base.js
  js/client.js
  js/consumer.js
  js/kafka/kafka-client.js
  js/kafka/kafka-consumer.js
  js/kafka/kafka-producer.js
  js/kafka/kafka-retry-consumer.js
  js/producer.js
  test/api/kafka.js
Labels: enhancement, fast-track

#14 Update trigger and bind documentation
  README.md
Labels: documentation, enhancement

#16 List topics
  js/base.js
  js/consumer.js
  js/kafka/kafka-consumer.js
  js/kafka/kafka-producer.js
  js/producer.js
  types/base.d.ts
  types/consumer.d.ts
  types/producer.d.ts
Labels: enhancement

#17 Document multiple bind
  README.md
Labels: documentation, enhancement

#18 fix: check if options are undefined
  js/kafka/kafka-client.js
Labels: bug

#19 Optional metadata fields
  types/base.d.ts
Labels: enhancement

#20 autoConfirm and run are optional
  types/base.d.ts
Labels: bug
